# Thanks to https://github.com/obsidian-tasks-group/obsidian-tasks for the
# workflow "starter template"!

name: Release Obsidian Plugin
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*" # Push events to matching any tag format, i.e. 1.0, 20.15.10
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x" # You might need to adjust this value to your own version

      # Get the version number and put it in a variable
      - name: Get Version
        id: version
        run: |
          echo "name=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT

      # Build the plugin
      - name: Build
        id: build
        run: |
          yarn
          yarn run build

      # Package the required files into a zip
      - name: Package
        run: |
          mkdir ${{ github.event.repository.name }}
          cp main.js manifest.json README.md ${{ github.event.repository.name }}
          zip -r ${{ github.event.repository.name }}-${{ steps.version.outputs.name }}.zip ${{ github.event.repository.name }}

      # Create the release on github
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ steps.version.outputs.name }}
          tag_name: ${{ github.ref }}
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ${{ github.event.repository.name }}-${{ steps.version.outputs.name }}.zip
            main.js
            manifest.json
